<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Municipality;

class MunicipalitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $municipalities = [
            // Ilocos Norte
            ['name' => 'Adams', 'province_id' => 1],
            ['name' => 'Bacarra', 'province_id' => 1],
            ['name' => 'Badoc', 'province_id' => 1],
            ['name' => 'Bangui', 'province_id' => 1],
            ['name' => 'Batac City', 'province_id' => 1],
            ['name' => 'Banna (Espiritu)', 'province_id' => 1],
            ['name' => 'Burgos', 'province_id' => 1],
            ['name' => 'Carasi', 'province_id' => 1],
            ['name' => 'Currimao', 'province_id' => 1],
            ['name' => 'Dingras', 'province_id' => 1],
            ['name' => 'Dumalneg', 'province_id' => 1],
            ['name' => 'Laoag City', 'province_id' => 1],
            ['name' => 'Marcos', 'province_id' => 1],
            ['name' => 'Nueva Era', 'province_id' => 1],
            ['name' => 'Pagudpud', 'province_id' => 1],
            ['name' => 'Paoay (Paaoay)', 'province_id' => 1],
            ['name' => 'Pasuquin', 'province_id' => 1],
            ['name' => 'Piddig', 'province_id' => 1],
            ['name' => 'Pinili', 'province_id' => 1],
            ['name' => 'San Nicolas', 'province_id' => 1],
            ['name' => 'Sarrat', 'province_id' => 1],
            ['name' => 'Solsona', 'province_id' => 1],
            ['name' => 'Vintar', 'province_id' => 1],

            // Ilocos Sur
            ['name' => 'Alilem', 'province_id' => 2],
            ['name' => 'Banayoyo', 'province_id' => 2],
            ['name' => 'Bantay', 'province_id' => 2],
            ['name' => 'Burgos', 'province_id' => 2],
            ['name' => 'Cabugao', 'province_id' => 2],
            ['name' => 'Candon City', 'province_id' => 2],
            ['name' => 'Caoayan', 'province_id' => 2],
            ['name' => 'Cervantes', 'province_id' => 2],
            ['name' => 'Galimuyod', 'province_id' => 2],
            ['name' => 'Gregorio Del Pilar (Concepcion)', 'province_id' => 2],
            ['name' => 'Lidlidda', 'province_id' => 2],
            ['name' => 'Magsingal', 'province_id' => 2],
            ['name' => 'Nagbukel', 'province_id' => 2],
            ['name' => 'Narvacan', 'province_id' => 2],
            ['name' => 'Quirino (Angkaki)', 'province_id' => 2],
            ['name' => 'Salcedo (Bauang)', 'province_id' => 2],
            ['name' => 'San Emilio', 'province_id' => 2],
            ['name' => 'San Esteban', 'province_id' => 2],
            ['name' => 'San Ildefonso (Sto. Domingo)', 'province_id' => 2],
            ['name' => 'San Juan (Lapog)', 'province_id' => 2],
            ['name' => 'San Vicente', 'province_id' => 2],
            ['name' => 'Santa', 'province_id' => 2],
            ['name' => 'Santa Catalina', 'province_id' => 2],
            ['name' => 'Santa Cruz', 'province_id' => 2],
            ['name' => 'Santiago (Quirino)', 'province_id' => 2],
            ['name' => 'Santo Domingo (Navarro)', 'province_id' => 2],
            ['name' => 'Sigay', 'province_id' => 2],
            ['name' => 'Sinait', 'province_id' => 2],
            ['name' => 'Suyo', 'province_id' => 2],
            ['name' => 'Tagudin', 'province_id' => 2],
            ['name' => 'Santa Lucia', 'province_id' => 2],
            ['name' => 'Vigan City', 'province_id' => 2],
            
            // La Union
            ['name' => 'Agoo', 'province_id' => 3],
            ['name' => 'Aringay', 'province_id' => 3],
            ['name' => 'Bacnotan', 'province_id' => 3],
            ['name' => 'Bagulin', 'province_id' => 3],
            ['name' => 'Balaoan', 'province_id' => 3],
            ['name' => 'Bangar', 'province_id' => 3],
            ['name' => 'Bauang', 'province_id' => 3],
            ['name' => 'Burgos', 'province_id' => 3],
            ['name' => 'Caba', 'province_id' => 3],
            ['name' => 'Luna', 'province_id' => 3],
            ['name' => 'Naguilian', 'province_id' => 3],
            ['name' => 'Pugo', 'province_id' => 3],
            ['name' => 'Rosario', 'province_id' => 3],
            ['name' => 'San Fernando City (Capital)', 'province_id' => 3],
            ['name' => 'San Gabriel', 'province_id' => 3],
            ['name' => 'San Juan (La Union)', 'province_id' => 3],
            ['name' => 'Santol', 'province_id' => 3],
            ['name' => 'Sudipen', 'province_id' => 3],
            ['name' => 'Tubao', 'province_id' => 3],

            //Pangasinan
            ['name' => 'Agno', 'province_id' => 4],
            ['name' => 'Aguilar', 'province_id' => 4],
            ['name' => 'Alaminos City', 'province_id' => 4],
            ['name' => 'Alcala', 'province_id' => 4],
            ['name' => 'Anda', 'province_id' => 4],
            ['name' => 'Asingan', 'province_id' => 4],
            ['name' => 'Balungao', 'province_id' => 4],
            ['name' => 'Bani', 'province_id' => 4],
            ['name' => 'Basista', 'province_id' => 4],
            ['name' => 'Bautista', 'province_id' => 4],
            ['name' => 'Bayambang', 'province_id' => 4],
            ['name' => 'Binalonan', 'province_id' => 4],
            ['name' => 'Binmaley', 'province_id' => 4],
            ['name' => 'Bolinao', 'province_id' => 4],
            ['name' => 'Bugallon', 'province_id' => 4],
            ['name' => 'Burgos (Patar)', 'province_id' => 4],
            ['name' => 'Calasiao', 'province_id' => 4],
            ['name' => 'Dasol', 'province_id' => 4],
            ['name' => 'Dagupan City', 'province_id' => 4],
            ['name' => 'Infanta', 'province_id' => 4],
            ['name' => 'Labrador', 'province_id' => 4],
            ['name' => 'Laoac', 'province_id' => 4],
            ['name' => 'Lingayen (Capital)', 'province_id' => 4],
            ['name' => 'Mabini (Pangasinan)', 'province_id' => 4],
            ['name' => 'Malasiqui', 'province_id' => 4],
            ['name' => 'Manaoag', 'province_id' => 4],
            ['name' => 'Mangaldan', 'province_id' => 4],
            ['name' => 'Mangatarem', 'province_id' => 4],
            ['name' => 'Mapandan', 'province_id' => 4],
            ['name' => 'Natividad', 'province_id' => 4],
            ['name' => 'Pozorrubio', 'province_id' => 4],
            ['name' => 'Rosales', 'province_id' => 4],
            ['name' => 'San Carlos City (Poblacion)', 'province_id' => 4],
            ['name' => 'San Fabian', 'province_id' => 4],
            ['name' => 'San Jacinto', 'province_id' => 4],
            ['name' => 'San Manuel', 'province_id' => 4],
            ['name' => 'San Nicolas', 'province_id' => 4],
            ['name' => 'San Quintin', 'province_id' => 4],
            ['name' => 'Santa Barbara', 'province_id' => 4],
            ['name' => 'Santa Maria', 'province_id' => 4],
            ['name' => 'Santo Tomas (Pangasinan)', 'province_id' => 4],
            ['name' => 'Sison', 'province_id' => 4],
            ['name' => 'Sual', 'province_id' => 4],
            ['name' => 'Tayug', 'province_id' => 4],
            ['name' => 'Umingan', 'province_id' => 4],
            ['name' => 'Urbiztondo', 'province_id' => 4],
            ['name' => 'Urdaneta City', 'province_id' => 4],
            ['name' => 'Villasis', 'province_id' => 4],

            //Batanes
            ['name' => 'Basco', 'province_id' => 5],
            ['name' => 'Itbayat', 'province_id' => 5],
            ['name' => 'Ivana', 'province_id' => 5],
            ['name' => 'Mahatao', 'province_id' => 5],
            ['name' => 'Sabtang', 'province_id' => 5],
            ['name' => 'Uyugan', 'province_id' => 5],

            // Cagayan
            ['name' => 'Abulug', 'province_id' => 6],
            ['name' => 'Alcala', 'province_id' => 6],
            ['name' => 'Allacapan', 'province_id' => 6],
            ['name' => 'Amulung', 'province_id' => 6],
            ['name' => 'Aparri', 'province_id' => 6],
            ['name' => 'Baggao', 'province_id' => 6],
            ['name' => 'Ballesteros', 'province_id' => 6],
            ['name' => 'Buguey', 'province_id' => 6],
            ['name' => 'Calayan', 'province_id' => 6],
            ['name' => 'Camalaniugan', 'province_id' => 6],
            ['name' => 'Claveria', 'province_id' => 6],
            ['name' => 'Enrile', 'province_id' => 6],
            ['name' => 'Gattaran', 'province_id' => 6],
            ['name' => 'Gonzaga', 'province_id' => 6],
            ['name' => 'Iguig', 'province_id' => 6],
            ['name' => 'Lal-lo (La Sallete)', 'province_id' => 6],
            ['name' => 'Lasam', 'province_id' => 6],
            ['name' => 'Pamplona (Cagayan)', 'province_id' => 6],
            ['name' => 'Peñablanca', 'province_id' => 6],
            ['name' => 'Piat', 'province_id' => 6],
            ['name' => 'Rizal (Piat)', 'province_id' => 6],
            ['name' => 'Sanchez-Mira (Sanchez Mira)', 'province_id' => 6],
            ['name' => 'Santa Ana (San Antonio)', 'province_id' => 6],
            ['name' => 'Santa Praxedes (Praxedes)', 'province_id' => 6],
            ['name' => 'Santa Teresita (Teresita)', 'province_id' => 6],
            ['name' => 'Santo Niño (San Lorenzo)', 'province_id' => 6],
            ['name' => 'Solana', 'province_id' => 6],
            ['name' => 'Tuguegarao City', 'province_id' => 6],
            ['name' => 'Tuao', 'province_id' => 6],

            // Isabela
            ['name' => 'Alicia', 'province_id' => 7],
            ['name' => 'Angadanan', 'province_id' => 7],
            ['name' => 'Aurora', 'province_id' => 7],
            ['name' => 'Benito Soliven', 'province_id' => 7],
            ['name' => 'Burgos (San Mariano)', 'province_id' => 7],
            ['name' => 'Cabagan', 'province_id' => 7],
            ['name' => 'Cauayan City', 'province_id' => 7],
            ['name' => 'Cordon', 'province_id' => 7],
            ['name' => 'Delfin Albano (Magsaysay)', 'province_id' => 7],
            ['name' => 'Dinapigue', 'province_id' => 7],
            ['name' => 'Divilacan', 'province_id' => 7],
            ['name' => 'Gamu', 'province_id' => 7],
            ['name' => 'Ilagan City (Capital)', 'province_id' => 7],
            ['name' => 'Jones', 'province_id' => 7],
            ['name' => 'Luna', 'province_id' => 7],
            ['name' => 'Maconacon', 'province_id' => 7],
            ['name' => 'Mallig', 'province_id' => 7],
            ['name' => 'Naguilian (Isabela)', 'province_id' => 7],
            ['name' => 'Palanan', 'province_id' => 7],
            ['name' => 'Quezon (Isabela)', 'province_id' => 7],
            ['name' => 'Quirino (Isabela)', 'province_id' => 7],
            ['name' => 'Ramon', 'province_id' => 7],
            ['name' => 'Reina Mercedes', 'province_id' => 7],
            ['name' => 'Roxas (Isabela)', 'province_id' => 7],
            ['name' => 'San Agustin (Isabela)', 'province_id' => 7],
            ['name' => 'San Guillermo', 'province_id' => 7],
            ['name' => 'San Isidro (Isabela)', 'province_id' => 7],
            ['name' => 'San Manuel (Isabela)', 'province_id' => 7],
            ['name' => 'San Mariano', 'province_id' => 7],
            ['name' => 'San Mateo (Isabela)', 'province_id' => 7],
            ['name' => 'San Pablo (Isabela)', 'province_id' => 7],
            ['name' => 'Santa Maria (Isabela)', 'province_id' => 7],
            ['name' => 'Santiago City', 'province_id' => 7],
            ['name' => 'Tumauini', 'province_id' => 7],

            // Nueva Vizcaya
            ['name' => 'Ambaguio', 'province_id' => 8],
            ['name' => 'Alfonso Castañeda', 'province_id' => 8],
            ['name' => 'Aritao', 'province_id' => 8],
            ['name' => 'Bagabag', 'province_id' => 8],
            ['name' => 'Bambang', 'province_id' => 8],
            ['name' => 'Bayombong (Capital)', 'province_id' => 8],
            ['name' => 'Diadi', 'province_id' => 8],
            ['name' => 'Dupax del Norte', 'province_id' => 8],
            ['name' => 'Dupax del Sur', 'province_id' => 8],
            ['name' => 'Kasibu', 'province_id' => 8],
            ['name' => 'Kayapa', 'province_id' => 8],
            ['name' => 'Quezon (Nueva Vizcaya)', 'province_id' => 8],
            ['name' => 'Santa Fe (Nueva Vizcaya)', 'province_id' => 8],
            ['name' => 'Solano ', 'province_id' => 8],
            ['name' => 'Villaverde', 'province_id' => 8],

            //Quirino
            ['name' => 'Aglipay', 'province_id' => 9],
            ['name' => 'Cabarroguis (Capital)', 'province_id' => 9],
            ['name' => 'Diffun', 'province_id' => 9],
            ['name' => 'Maddela', 'province_id' => 9],
            ['name' => 'Nagtipunan', 'province_id' => 9],
            ['name' => 'Saguday', 'province_id' => 9],

            //Aurora
            ['name' => 'Baler (Capital)', 'province_id' => 10],
            ['name' => 'Casiguran', 'province_id' => 10],
            ['name' => 'Dilasag', 'province_id' => 10],
            ['name' => 'Dinalungan', 'province_id' => 10],
            ['name' => 'Dipaculao', 'province_id' => 10],
            ['name' => 'Maria Aurora', 'province_id' => 10],
            ['name' => 'San Luis (Aurora)', 'province_id' => 10],
            ['name' => 'San Onofre (Aurora)', 'province_id' => 10],
            ['name' => 'Sierra Madre (Aurora)', 'province_id' => 10],

            //Bataan
            ['name' => 'Abucay', 'province_id' => 11],
            ['name' => 'Bagac', 'province_id' => 11],
            ['name' => 'Balanga City (Capital)', 'province_id' => 11],
            ['name' => 'Dinalupihan', 'province_id' => 11],
            ['name' => 'Hermosa', 'province_id' => 11],
            ['name' => 'Limay', 'province_id' => 11],
            ['name' => 'Mariveles', 'province_id' => 11],
            ['name' => 'Morong', 'province_id' => 11],
            ['name' => 'Orani', 'province_id' => 11],
            ['name' => 'Orion', 'province_id' => 11],
            ['name' => 'Pilar (Bataan)', 'province_id' => 11],
            ['name' => 'Samal (Bataan)', 'province_id' => 11],
            ['name' => 'Santo Tomas (Bataan)', 'province_id' => 11],

            //Bulacan
           // Bulacan
            ['name' => 'Angat', 'province_id' => 12],
            ['name' => 'Balagtas', 'province_id' => 12],
            ['name' => 'Baliwag', 'province_id' => 12],
            ['name' => 'Bocaue', 'province_id' => 12],
            ['name' => 'Bulacan', 'province_id' => 12],
            ['name' => 'Calumpit', 'province_id' => 12],
            ['name' => 'Doña Remedios Trinidad', 'province_id' => 12],
            ['name' => 'Guiguinto', 'province_id' => 12],
            ['name' => 'Hagonoy', 'province_id' => 12],
            ['name' => 'Malolos City (Capital)', 'province_id' => 12],
            ['name' => 'Marilao', 'province_id' => 12],
            ['name' => 'Meycauayan City', 'province_id' => 12],
            ['name' => 'Norzagaray', 'province_id' => 12],
            ['name' => 'Obando', 'province_id' => 12],
            ['name' => 'Pandi', 'province_id' => 12],
            ['name' => 'Plaridel', 'province_id' => 12],
            ['name' => 'Pulilan', 'province_id' => 12],
            ['name' => 'San Ildefonso', 'province_id' => 12],
            ['name' => 'San Miguel', 'province_id' => 12],
            ['name' => 'San Rafael', 'province_id' => 12],
            ['name' => 'Santa Maria', 'province_id' => 12],

            // Nueva Ecija
            ['name' => 'Aliaga', 'province_id' => 13],
            ['name' => 'Bongabon', 'province_id' => 13],
            ['name' => 'Cabanatuan City', 'province_id' => 13],
            ['name' => 'Cabiao', 'province_id' => 13],
            ['name' => 'Carranglan', 'province_id' => 13],
            ['name' => 'Cuyapo', 'province_id' => 13],
            ['name' => 'Gabaldon', 'province_id' => 13],
            ['name' => 'Gapan City', 'province_id' => 13],
            ['name' => 'General Mamerto Natividad', 'province_id' => 13],
            ['name' => 'General Tinio', 'province_id' => 13],
            ['name' => 'Guimba', 'province_id' => 13],
            ['name' => 'Jaen', 'province_id' => 13],
            ['name' => 'Laur', 'province_id' => 13],
            ['name' => 'Licab', 'province_id' => 13],
            ['name' => 'Llanera', 'province_id' => 13],
            ['name' => 'Lupao', 'province_id' => 13],
            ['name' => 'Muñoz City', 'province_id' => 13],
            ['name' => 'Nampicuan', 'province_id' => 13],
            ['name' => 'Palayan City (Capital)', 'province_id' => 13],
            ['name' => 'Pantabangan', 'province_id' => 13],
            ['name' => 'Peñaranda', 'province_id' => 13],
            ['name' => 'Quezon', 'province_id' => 13],
            ['name' => 'Rizal', 'province_id' => 13],
            ['name' => 'San Antonio', 'province_id' => 13],
            ['name' => 'San Isidro', 'province_id' => 13],
            ['name' => 'San Leonardo', 'province_id' => 13],
            ['name' => 'Santa Rosa', 'province_id' => 13],
            ['name' => 'Santo Domingo', 'province_id' => 13],
            ['name' => 'Talavera', 'province_id' => 13],
            ['name' => 'Talugtug', 'province_id' => 13],
            ['name' => 'Zaragoza', 'province_id' => 13],


            // Pampanga
            ['name' => 'Angeles City', 'province_id' => 14],
            ['name' => 'Apalit', 'province_id' => 14],
            ['name' => 'Arayat', 'province_id' => 14],
            ['name' => 'Bacolor', 'province_id' => 14],
            ['name' => 'Candaba', 'province_id' => 14],
            ['name' => 'Floridablanca', 'province_id' => 14],
            ['name' => 'Guagua', 'province_id' => 14],
            ['name' => 'Lubao', 'province_id' => 14],
            ['name' => 'Mabalacat City', 'province_id' => 14],
            ['name' => 'Macabebe', 'province_id' => 14],
            ['name' => 'Magalang', 'province_id' => 14],
            ['name' => 'Masantol', 'province_id' => 14],
            ['name' => 'Mexico', 'province_id' => 14],
            ['name' => 'Minalin', 'province_id' => 14],
            ['name' => 'Porac', 'province_id' => 14],
            ['name' => 'San Fernando City (Capital)', 'province_id' => 14],
            ['name' => 'San Luis', 'province_id' => 14],
            ['name' => 'San Simon', 'province_id' => 14],
            ['name' => 'Santa Ana', 'province_id' => 14],
            ['name' => 'Santa Rita', 'province_id' => 14],
            ['name' => 'Santo Tomas', 'province_id' => 14],
            ['name' => 'Sasmuan', 'province_id' => 14],

            // Tarlac
            ['name' => 'Anao', 'province_id' => 15],
            ['name' => 'Bamban', 'province_id' => 15],
            ['name' => 'Camiling', 'province_id' => 15],
            ['name' => 'Capas', 'province_id' => 15],
            ['name' => 'Concepcion', 'province_id' => 15],
            ['name' => 'Gerona', 'province_id' => 15],
            ['name' => 'La Paz', 'province_id' => 15],
            ['name' => 'Mayantoc', 'province_id' => 15],
            ['name' => 'Moncada', 'province_id' => 15],
            ['name' => 'Paniqui', 'province_id' => 15],
            ['name' => 'Pura', 'province_id' => 15],
            ['name' => 'Ramos', 'province_id' => 15],
            ['name' => 'San Clemente', 'province_id' => 15],
            ['name' => 'San Jose', 'province_id' => 15],
            ['name' => 'San Manuel', 'province_id' => 15],
            ['name' => 'Santa Ignacia', 'province_id' => 15],
            ['name' => 'Tarlac City (Capital)', 'province_id' => 15],
            ['name' => 'Victoria', 'province_id' => 15],

            // Zambales
            ['name' => 'Botolan', 'province_id' => 16],
            ['name' => 'Cabangan', 'province_id' => 16],
            ['name' => 'Candelaria', 'province_id' => 16],
            ['name' => 'Castillejos', 'province_id' => 16],
            ['name' => 'Iba (Capital)', 'province_id' => 16],
            ['name' => 'Masinloc', 'province_id' => 16],
            ['name' => 'Olongapo City', 'province_id' => 16],
            ['name' => 'Palauig', 'province_id' => 16],
            ['name' => 'San Antonio', 'province_id' => 16],
            ['name' => 'San Felipe', 'province_id' => 16],
            ['name' => 'San Marcelino', 'province_id' => 16],
            ['name' => 'San Narciso', 'province_id' => 16],
            ['name' => 'Santa Cruz', 'province_id' => 16],
            ['name' => 'Subic', 'province_id' => 16],

            //batangas
            ['name' => 'Agoncillo', 'province_id' => 17],
            ['name' => 'Alitagtag', 'province_id' => 17],
            ['name' => 'Balayan', 'province_id' => 17],
            ['name' => 'Batangas City (Capital)', 'province_id' => 17],
            ['name' => 'Bauan', 'province_id' => 17],
            ['name' => 'Calaca', 'province_id' => 17],
            ['name' => 'Calatagan', 'province_id' => 17],
            ['name' => 'Cuenca', 'province_id' => 17],
            ['name' => 'Ibaan', 'province_id' => 17],
            ['name' => 'Laurel', 'province_id' => 17],
            ['name' => 'Lemery', 'province_id' => 17],
            ['name' => 'Lian', 'province_id' => 17],
            ['name' => 'Lipa City', 'province_id' => 17],
            ['name' => 'Mabini (Batangas)', 'province_id' => 17],
            ['name' => 'Malvar', 'province_id' => 17],
            ['name' => 'Mataasnakahoy', 'province_id' => 17],
            ['name' => 'Nasugbu', 'province_id' => 17],
            ['name' => 'Padre Garcia', 'province_id' => 17],
            ['name' => 'Rosario (Batangas)', 'province_id' => 17],
            ['name' => 'San Jose (Batangas)', 'province_id' => 17],
            ['name' => 'San Juan (Batangas)', 'province_id' => 17],
            ['name' => 'San Luis (Batangas)', 'province_id' => 17],
            ['name' => 'San Nicolas (Batangas)', 'province_id' => 17],
            ['name' => 'San Pascual (Batangas)', 'province_id' => 17],
            ['name' => 'Santa Teresita (Batangas)', 'province_id' => 17],
            ['name' => 'Santo Tomas (Batangas)', 'province_id' => 17],
            ['name' => 'Taal', 'province_id' => 17],
            ['name' => 'Talisay (Batangas)', 'province_id' => 17],
            ['name' => 'Tanauan City', 'province_id' => 17],
            ['name' => 'Taysan', 'province_id' => 17],
            ['name' => 'Tingloy', 'province_id' => 17],
            ['name' => 'Tuy', 'province_id' => 17],

            //Cavite
            ['name' => 'Alfonso', 'province_id' => 18],
            ['name' => 'Amadeo', 'province_id' => 18],
            ['name' => 'Bacoor City', 'province_id' => 18],
            ['name' => 'Carmona', 'province_id' => 18],
            ['name' => 'Cavite City (Capital)', 'province_id' => 18],
            ['name' => 'Dasmariñas City', 'province_id' => 18],
            ['name' => 'General Emilio Aguinaldo (Bailen)', 'province_id' => 18],
            ['name' => 'General Mariano Alvarez (GMA)', 'province_id' => 18],
            ['name' => 'General Trias City', 'province_id' => 18],
            ['name' => 'Imus City', 'province_id' => 18],
            ['name' => 'Indang', 'province_id' => 18],
            ['name' => 'Kawit', 'province_id' => 18],
            ['name' => 'Magallanes (Cavite)', 'province_id' => 18],
            ['name' => 'Maragondon', 'province_id' => 18],
            ['name' => 'Mendez (Mendez-Nuñez)', 'province_id' => 18],
            ['name' => 'Naic', 'province_id' => 18],
            ['name' => 'Noveleta', 'province_id' => 18],
            ['name' => 'Rosario (Cavite)', 'province_id' => 18],
            ['name' => 'Silang', 'province_id' => 18],
            ['name' => 'Tagaytay City', 'province_id' => 18],
            ['name' => 'Tanza', 'province_id' => 18],
            ['name' => 'Ternate (Cavite)', 'province_id' => 18],
            ['name' => 'Trece Martires City', 'province_id' => 18],

           // Laguna
            ['name' => 'Alaminos', 'province_id' => 19],
            ['name' => 'Bay', 'province_id' => 19],
            ['name' => 'Biñan City', 'province_id' => 19],
            ['name' => 'Calamba City', 'province_id' => 19],
            ['name' => 'Calauan', 'province_id' => 19],
            ['name' => 'Cavinti', 'province_id' => 19],
            ['name' => 'Famy', 'province_id' => 19],
            ['name' => 'Kalayaan', 'province_id' => 19],
            ['name' => 'Liliw', 'province_id' => 19],
            ['name' => 'Los Baños', 'province_id' => 19],
            ['name' => 'Luisiana', 'province_id' => 19],
            ['name' => 'Lumban', 'province_id' => 19],
            ['name' => 'Mabitac', 'province_id' => 19],
            ['name' => 'Magdalena', 'province_id' => 19],
            ['name' => 'Majayjay', 'province_id' => 19],
            ['name' => 'Nagcarlan', 'province_id' => 19],
            ['name' => 'Paete', 'province_id' => 19],
            ['name' => 'Pagsanjan', 'province_id' => 19],
            ['name' => 'Pakil', 'province_id' => 19],
            ['name' => 'Pangil', 'province_id' => 19],
            ['name' => 'Pila', 'province_id' => 19],
            ['name' => 'Rizal', 'province_id' => 19],
            ['name' => 'San Pablo City', 'province_id' => 19],
            ['name' => 'San Pedro City', 'province_id' => 19],
            ['name' => 'Santa Cruz (Capital)', 'province_id' => 19],
            ['name' => 'Santa Maria', 'province_id' => 19],
            ['name' => 'Siniloan', 'province_id' => 19],
            ['name' => 'Victoria', 'province_id' => 19],

            // Quezon
            ['name' => 'Agdangan', 'province_id' => 20],
            ['name' => 'Alabat', 'province_id' => 20],
            ['name' => 'Atimonan', 'province_id' => 20],
            ['name' => 'Buenavista (Quezon)', 'province_id' => 20],
            ['name' => 'Burdeos', 'province_id' => 20],
            ['name' => 'Calauag', 'province_id' => 20],
            ['name' => 'Candelaria', 'province_id' => 20],
            ['name' => 'Catanauan', 'province_id' => 20],
            ['name' => 'Dolores (Quezon)', 'province_id' => 20],
            ['name' => 'General Luna (Quezon)', 'province_id' => 20],
            ['name' => 'General Nakar', 'province_id' => 20],
            ['name' => 'Guinayangan', 'province_id' => 20],
            ['name' => 'Gumaca', 'province_id' => 20],
            ['name' => 'Infanta', 'province_id' => 20],
            ['name' => 'Jomalig', 'province_id' => 20],
            ['name' => 'Lopez (Quezon)', 'province_id' => 20],
            ['name' => 'Lucban', 'province_id' => 20],
            ['name' => 'Lucena City', 'province_id' => 20],
            ['name' => 'Macalelon', 'province_id' => 20],
            ['name' => 'Mauban', 'province_id' => 20],
            ['name' => 'Mulanay', 'province_id' => 20],
            ['name' => 'Padre Burgos (Quezon)', 'province_id' => 20],
            ['name' => 'Pagbilao', 'province_id' => 20],
            ['name' => 'Panukulan', 'province_id' => 20],
            ['name' => 'Patnanungan', 'province_id' => 20],
            ['name' => 'Perez (Quezon)', 'province_id' => 20],
            ['name' => 'Pitogo (Quezon)', 'province_id' => 20],
            ['name' => 'Plaridel (Quezon)', 'province_id' => 20],
            ['name' => 'Polillo', 'province_id' => 20],
            ['name' => 'Quezon', 'province_id' => 20],
            ['name' => 'Real (Quezon)', 'province_id' => 20],
            ['name' => 'Sampaloc (Quezon)', 'province_id' => 20],
            ['name' => 'San Andres (Quezon)', 'province_id' => 20],
            ['name' => 'San Antonio (Quezon)', 'province_id' => 20],
            ['name' => 'San Francisco (Quezon)', 'province_id' => 20],
            ['name' => 'San Narciso (Quezon)', 'province_id' => 20],
            ['name' => 'San Pascual (Quezon)', 'province_id' => 20],
            ['name' => 'Sariaya', 'province_id' => 20],
            ['name' => 'Tagkawayan', 'province_id' => 20],
            ['name' => 'Tayabas City', 'province_id' => 20],
            ['name' => 'Tiaong', 'province_id' => 20],
            ['name' => 'Unisan', 'province_id' => 20],

            // Rizal
            ['name' => 'Angono', 'province_id' => 21],
            ['name' => 'Antipolo City (Capital)', 'province_id' => 21],
            ['name' => 'Baras', 'province_id' => 21],
            ['name' => 'Binangonan', 'province_id' => 21],
            ['name' => 'Cainta', 'province_id' => 21],
            ['name' => 'Cardona', 'province_id' => 21],
            ['name' => 'Jalajala', 'province_id' => 21],
            ['name' => 'Morong', 'province_id' => 21],
            ['name' => 'Pililla', 'province_id' => 21],
            ['name' => 'Rodriguez', 'province_id' => 21],
            ['name' => 'San Mateo', 'province_id' => 21],
            ['name' => 'Tanay', 'province_id' => 21],
            ['name' => 'Taytay', 'province_id' => 21],
            ['name' => 'Teresa', 'province_id' => 21],

            //Marinduque
            ['name' => 'Boac (Capital)', 'province_id' => 22],
            ['name' => 'Buenavista (Marinduque)', 'province_id' => 22],
            ['name' => 'Gasan', 'province_id' => 22],
            ['name' => 'Mogpog', 'province_id' => 22],
            ['name' => 'Santa Cruz (Marinduque)', 'province_id' => 22],
            ['name' => 'Torrijos', 'province_id' => 22],

            //Occidental Mindoro
            ['name' => 'Abra de Ilog', 'province_id' => 23],
            ['name' => 'Calintaan', 'province_id' => 23],
            ['name' => 'Looc', 'province_id' => 23],
            ['name' => 'Magsaysay (Occidental Mindoro)', 'province_id' => 23],
            ['name' => 'Mamburao (Capital)', 'province_id' => 23],
            ['name' => 'Paluan', 'province_id' => 23],
            ['name' => 'Rizal (Occidental Mindoro)', 'province_id' => 23],
            ['name' => 'Sablayan', 'province_id' => 23],
            ['name' => 'Santa Cruz (Occidental Mindoro)', 'province_id' => 23],
            ['name' => 'Victoria (Occidental Mindoro)', 'province_id' => 23],

           // Oriental Mindoro
            ['name' => 'Baco', 'province_id' => 24],
            ['name' => 'Bansud', 'province_id' => 24],
            ['name' => 'Bongabong', 'province_id' => 24],
            ['name' => 'Bulalacao', 'province_id' => 24],
            ['name' => 'Calapan City (Capital)', 'province_id' => 24],
            ['name' => 'Gloria', 'province_id' => 24],
            ['name' => 'Mansalay', 'province_id' => 24],
            ['name' => 'Naujan', 'province_id' => 24],
            ['name' => 'Pinamalayan', 'province_id' => 24],
            ['name' => 'Pola', 'province_id' => 24],
            ['name' => 'Puerto Galera', 'province_id' => 24],
            ['name' => 'Roxas', 'province_id' => 24],
            ['name' => 'San Teodoro', 'province_id' => 24],
            ['name' => 'San Jose', 'province_id' => 24],
            ['name' => 'Socorro', 'province_id' => 24],
            ['name' => 'Taytay', 'province_id' => 24],
            ['name' => 'Victoria', 'province_id' => 24],

            // Palawan
            ['name' => 'Aborlan', 'province_id' => 25],
            ['name' => 'Agutaya', 'province_id' => 25],
            ['name' => 'Araceli', 'province_id' => 25],
            ['name' => 'Balabac', 'province_id' => 25],
            ['name' => 'Bataraza', 'province_id' => 25],
            ['name' => 'Brooke\'s Point', 'province_id' => 25],
            ['name' => 'Busuanga', 'province_id' => 25],
            ['name' => 'Cagayancillo', 'province_id' => 25],
            ['name' => 'Coron', 'province_id' => 25],
            ['name' => 'Culion', 'province_id' => 25],
            ['name' => 'Cuyo', 'province_id' => 25],
            ['name' => 'Dumaran', 'province_id' => 25],
            ['name' => 'El Nido', 'province_id' => 25],
            ['name' => 'Kalayaan', 'province_id' => 25],
            ['name' => 'Linapacan', 'province_id' => 25],
            ['name' => 'Magsaysay', 'province_id' => 25],
            ['name' => 'Narra', 'province_id' => 25],
            ['name' => 'Puerto Princesa City (Capital)', 'province_id' => 25],
            ['name' => 'Quezon', 'province_id' => 25],
            ['name' => 'Rizal', 'province_id' => 25],
            ['name' => 'Roxas', 'province_id' => 25],
            ['name' => 'San Vicente', 'province_id' => 25],
            ['name' => 'Sofronio Española', 'province_id' => 25],
            ['name' => 'Taytay', 'province_id' => 25],

            // Romblon
            ['name' => 'Alcantara', 'province_id' => 26],
            ['name' => 'Banton', 'province_id' => 26],
            ['name' => 'Cajidiocan', 'province_id' => 26],
            ['name' => 'Calatrava', 'province_id' => 26],
            ['name' => 'Concepcion', 'province_id' => 26],
            ['name' => 'Corcuera', 'province_id' => 26],
            ['name' => 'Ferrol', 'province_id' => 26],
            ['name' => 'Looc', 'province_id' => 26],
            ['name' => 'Magdiwang', 'province_id' => 26],
            ['name' => 'Odiongan', 'province_id' => 26],
            ['name' => 'Romblon (Capital)', 'province_id' => 26],
            ['name' => 'San Agustin', 'province_id' => 26],
            ['name' => 'San Andres', 'province_id' => 26],
            ['name' => 'San Fernando', 'province_id' => 26],
            ['name' => 'San Jose', 'province_id' => 26],
            ['name' => 'Santa Fe', 'province_id' => 26],
            ['name' => 'Santa Maria', 'province_id' => 26],

            // Albay
            ['name' => 'Camalig', 'province_id' => 27],
            ['name' => 'Daraga', 'province_id' => 27],  // or 'Daraga (Locsin)' if preferred
            ['name' => 'Guinobatan', 'province_id' => 27],
            ['name' => 'Legazpi City (Capital)', 'province_id' => 27],
            ['name' => 'Libon', 'province_id' => 27],
            ['name' => 'Ligao City', 'province_id' => 27],
            ['name' => 'Malilipot', 'province_id' => 27],
            ['name' => 'Malinao', 'province_id' => 27],
            ['name' => 'Manito', 'province_id' => 27],
            ['name' => 'Oas', 'province_id' => 27],
            ['name' => 'Pio Duran', 'province_id' => 27],
            ['name' => 'Polangui', 'province_id' => 27],
            ['name' => 'Rapu-Rapu', 'province_id' => 27],
            ['name' => 'Santo Domingo', 'province_id' => 27],  // or 'Santo Domingo (Libog)'
            ['name' => 'Tabaco City', 'province_id' => 27],
            ['name' => 'Tiwi', 'province_id' => 27],


            // Camarines Norte
            ['name' => 'Basud', 'province_id' => 28],
            ['name' => 'Capalonga', 'province_id' => 28],
            ['name' => 'Daet (Capital)', 'province_id' => 28],
            ['name' => 'Jose Panganiban', 'province_id' => 28],
            ['name' => 'Labo', 'province_id' => 28],
            ['name' => 'Mercedes', 'province_id' => 28],
            ['name' => 'Paracale', 'province_id' => 28],
            ['name' => 'San Lorenzo Ruiz (Placer)', 'province_id' => 28],
            ['name' => 'San Vicente', 'province_id' => 28],
            ['name' => 'Talisay', 'province_id' => 28],
            ['name' => 'Vinzons', 'province_id' => 28],

            // Camarines Sur
            ['name' => 'Baao', 'province_id' => 29],
            ['name' => 'Bato', 'province_id' => 29],
            ['name' => 'Bombon', 'province_id' => 29],
            ['name' => 'Buhi', 'province_id' => 29],
            ['name' => 'Bula', 'province_id' => 29],
            ['name' => 'Cabusao', 'province_id' => 29],
            ['name' => 'Calabanga', 'province_id' => 29],
            ['name' => 'Canaman', 'province_id' => 29],
            ['name' => 'Caramoan', 'province_id' => 29],
            ['name' => 'Del Gallego', 'province_id' => 29],
            ['name' => 'Gainza', 'province_id' => 29],
            ['name' => 'Garchitorena', 'province_id' => 29],
            ['name' => 'Goa', 'province_id' => 29],
            ['name' => 'Iriga City', 'province_id' => 29],
            ['name' => 'Lagonoy', 'province_id' => 29],
            ['name' => 'Libmanan', 'province_id' => 29],
            ['name' => 'Lupi', 'province_id' => 29],
            ['name' => 'Magarao', 'province_id' => 29],
            ['name' => 'Milaor', 'province_id' => 29],
            ['name' => 'Minalabac', 'province_id' => 29],
            ['name' => 'Nabua', 'province_id' => 29],
            ['name' => 'Naga City (Capital)', 'province_id' => 29],
            ['name' => 'Ocampo', 'province_id' => 29],
            ['name' => 'Pamplona', 'province_id' => 29],
            ['name' => 'Pasacao', 'province_id' => 29],
            ['name' => 'Pili', 'province_id' => 29],
            ['name' => 'Presentacion', 'province_id' => 29],
            ['name' => 'Ragay', 'province_id' => 29],
            ['name' => 'Sagñay', 'province_id' => 29],
            ['name' => 'San Fernando', 'province_id' => 29],
            ['name' => 'San Jose', 'province_id' => 29],
            ['name' => 'Sipocot', 'province_id' => 29],
            ['name' => 'Siruma', 'province_id' => 29],
            ['name' => 'Tigaon', 'province_id' => 29],
            ['name' => 'Tinambac', 'province_id' => 29],


           // Catanduanes
            ['name' => 'Bagamanoc', 'province_id' => 30],
            ['name' => 'Baras (Catanduanes)', 'province_id' => 30],
            ['name' => 'Bato (Catanduanes)', 'province_id' => 30],
            ['name' => 'Caramoran', 'province_id' => 30],
            ['name' => 'Gigmoto', 'province_id' => 30],
            ['name' => 'Pandan (Catanduanes)', 'province_id' => 30],
            ['name' => 'San Andres (Catanduanes)', 'province_id' => 30],
            ['name' => 'San Miguel (Catanduanes)', 'province_id' => 30],
            ['name' => 'San Vicente (Catanduanes)', 'province_id' => 30],
            ['name' => 'Viga', 'province_id' => 30],
            ['name' => 'Virac (Capital)', 'province_id' => 30],


            // Masbate
            ['name' => 'Aroroy', 'province_id' => 31],
            ['name' => 'Balud', 'province_id' => 31],
            ['name' => 'Batuan', 'province_id' => 31],
            ['name' => 'Cataingan', 'province_id' => 31],
            ['name' => 'Claveria', 'province_id' => 31],
            ['name' => 'Dimasalang', 'province_id' => 31],
            ['name' => 'Esperanza', 'province_id' => 31],
            ['name' => 'Mandaon', 'province_id' => 31],
            ['name' => 'Masbate City (Capital)', 'province_id' => 31],
            ['name' => 'Milagros', 'province_id' => 31],
            ['name' => 'Mobo', 'province_id' => 31],
            ['name' => 'Monreal', 'province_id' => 31],
            ['name' => 'Palanas', 'province_id' => 31],
            ['name' => 'Pio V. Corpuz', 'province_id' => 31],
            ['name' => 'Placer', 'province_id' => 31],
            ['name' => 'San Fernando', 'province_id' => 31],
            ['name' => 'San Jacinto', 'province_id' => 31],
            ['name' => 'San Pascual', 'province_id' => 31],
            ['name' => 'Uson', 'province_id' => 31],
            ['name' => 'Cawayan', 'province_id' => 31],


            // Sorsogon
            ['name' => 'Barcelona', 'province_id' => 32],
            ['name' => 'Bulan', 'province_id' => 32],
            ['name' => 'Casiguran', 'province_id' => 32],
            ['name' => 'Donsol', 'province_id' => 32],
            ['name' => 'Gubat', 'province_id' => 32],
            ['name' => 'Irosin', 'province_id' => 32],
            ['name' => 'Juban', 'province_id' => 32],
            ['name' => 'Magallanes', 'province_id' => 32],
            ['name' => 'Matnog', 'province_id' => 32],
            ['name' => 'Pilar', 'province_id' => 32],
            ['name' => 'Prieto Diaz', 'province_id' => 32],
            ['name' => 'Santa Magdalena', 'province_id' => 32],
            ['name' => 'Sorsogon City (Capital)', 'province_id' => 32],
            ['name' => 'Bulusan', 'province_id' => 32],


            // Aklan
            ['name' => 'Altavas', 'province_id' => 33],
            ['name' => 'Balete', 'province_id' => 33],
            ['name' => 'Banga', 'province_id' => 33],
            ['name' => 'Batan', 'province_id' => 33],
            ['name' => 'Buruanga', 'province_id' => 33],
            ['name' => 'Ibajay', 'province_id' => 33],
            ['name' => 'Kalibo (Capital)', 'province_id' => 33],
            ['name' => 'Lezo', 'province_id' => 33],
            ['name' => 'Libacao', 'province_id' => 33],
            ['name' => 'Madalag', 'province_id' => 33],
            ['name' => 'Makato', 'province_id' => 33],
            ['name' => 'Malay', 'province_id' => 33],
            ['name' => 'Malinao', 'province_id' => 33],
            ['name' => 'Nabas', 'province_id' => 33],
            ['name' => 'New Washington', 'province_id' => 33],
            ['name' => 'Numancia', 'province_id' => 33],
            ['name' => 'Tangalan', 'province_id' => 33],
            ['name' => 'Libertad', 'province_id' => 33],

            // Antique
            ['name' => 'Anini-y', 'province_id' => 34],
            ['name' => 'Barbaza', 'province_id' => 34],
            ['name' => 'Belison', 'province_id' => 34],
            ['name' => 'Bugasong', 'province_id' => 34],
            ['name' => 'Culasi', 'province_id' => 34],
            ['name' => 'Hamtic', 'province_id' => 34],
            ['name' => 'Laua-an', 'province_id' => 34],
            ['name' => 'Libertad', 'province_id' => 34],
            ['name' => 'Pandan', 'province_id' => 34],
            ['name' => 'Patnongon', 'province_id' => 34],
            ['name' => 'San Jose de Buenavista (Capital)', 'province_id' => 34],
            ['name' => 'San Remigio', 'province_id' => 34],
            ['name' => 'Sibalom', 'province_id' => 34],
            ['name' => 'Tibiao', 'province_id' => 34],
            ['name' => 'Valderrama', 'province_id' => 34],
            ['name' => 'San Antonio', 'province_id' => 34],
            ['name' => 'San Pedro', 'province_id' => 34],


            // Capiz
            ['name' => 'Dao', 'province_id' => 35],
            ['name' => 'Dumalag', 'province_id' => 35],
            ['name' => 'Dumarao', 'province_id' => 35],
            ['name' => 'Ivisan', 'province_id' => 35],
            ['name' => 'Jamindan', 'province_id' => 35],
            ['name' => 'Maayon', 'province_id' => 35],
            ['name' => 'Mambusao', 'province_id' => 35],
            ['name' => 'Panay', 'province_id' => 35],
            ['name' => 'Panitan', 'province_id' => 35],
            ['name' => 'Pilar', 'province_id' => 35],
            ['name' => 'Pontevedra', 'province_id' => 35],
            ['name' => 'Roxas City (Capital)', 'province_id' => 35],
            ['name' => 'Sigma', 'province_id' => 35],
            ['name' => 'Tapaz', 'province_id' => 35],
            ['name' => 'Maasin', 'province_id' => 35],

            // Guimaras
            ['name' => 'Buenavista', 'province_id' => 36],
            ['name' => 'Jordan (Capital)', 'province_id' => 36],
            ['name' => 'Nueva Valencia', 'province_id' => 36],
            ['name' => 'San Lorenzo', 'province_id' => 36],
            ['name' => 'Sibunag', 'province_id' => 36],

            // Iloilo
            ['name' => 'Ajuy', 'province_id' => 37],
            ['name' => 'Alimodian', 'province_id' => 37],
            ['name' => 'Anilao', 'province_id' => 37],
            ['name' => 'Badiangan', 'province_id' => 37],
            ['name' => 'Balasan', 'province_id' => 37],
            ['name' => 'Banate', 'province_id' => 37],
            ['name' => 'Barotac Nuevo', 'province_id' => 37],
            ['name' => 'Barotac Viejo', 'province_id' => 37],
            ['name' => 'Batad', 'province_id' => 37],
            ['name' => 'Bingawan', 'province_id' => 37],
            ['name' => 'Cabatuan', 'province_id' => 37],
            ['name' => 'Calinog', 'province_id' => 37],
            ['name' => 'Carles', 'province_id' => 37],
            ['name' => 'Concepcion', 'province_id' => 37],
            ['name' => 'Dingle', 'province_id' => 37],
            ['name' => 'Dueñas', 'province_id' => 37],
            ['name' => 'Dumangas', 'province_id' => 37],
            ['name' => 'Estancia', 'province_id' => 37],
            ['name' => 'Guimbal', 'province_id' => 37],
            ['name' => 'Igbaras', 'province_id' => 37],
            ['name' => 'Janiuay', 'province_id' => 37],
            ['name' => 'Lambunao', 'province_id' => 37],
            ['name' => 'Leganes', 'province_id' => 37],
            ['name' => 'Lemery', 'province_id' => 37],
            ['name' => 'Lopez Jaena', 'province_id' => 37],
            ['name' => 'Maasin', 'province_id' => 37],
            ['name' => 'Mina', 'province_id' => 37],
            ['name' => 'New Lucena', 'province_id' => 37],
            ['name' => 'Oton', 'province_id' => 37],
            ['name' => 'Passi City', 'province_id' => 37],
            ['name' => 'Pototan', 'province_id' => 37],
            ['name' => 'San Dionisio', 'province_id' => 37],
            ['name' => 'San Enrique', 'province_id' => 37],
            ['name' => 'San Joaquin', 'province_id' => 37],
            ['name' => 'San Miguel', 'province_id' => 37],
            ['name' => 'San Rafael', 'province_id' => 37],
            ['name' => 'Santa Barbara', 'province_id' => 37],
            ['name' => 'Sara', 'province_id' => 37],
            ['name' => 'Tigbauan', 'province_id' => 37],
            ['name' => 'Tubungan', 'province_id' => 37],
            ['name' => 'Zarraga', 'province_id' => 37],
            ['name' => 'Iloilo City (Capital)', 'province_id' => 37],
            ['name' => 'Pavia', 'province_id' => 37],

            // Negros Occidental
            ['name' => 'Bacolod City (Capital)', 'province_id' => 38],
            ['name' => 'Bago City', 'province_id' => 38],
            ['name' => 'Binalbagan', 'province_id' => 38],
            ['name' => 'Cadiz City', 'province_id' => 38],
            ['name' => 'Calatrava', 'province_id' => 38],
            ['name' => 'Candoni', 'province_id' => 38],
            ['name' => 'Cauayan', 'province_id' => 38],
            ['name' => 'Enrique B. Magalona (Saravia)', 'province_id' => 38],
            ['name' => 'Escalante City', 'province_id' => 38],
            ['name' => 'Himamaylan City', 'province_id' => 38],
            ['name' => 'Hinoba-an (Asia)', 'province_id' => 38],
            ['name' => 'Ilog', 'province_id' => 38],
            ['name' => 'Isabela City', 'province_id' => 38],
            ['name' => 'Kabankalan City', 'province_id' => 38],
            ['name' => 'La Castellana', 'province_id' => 38],
            ['name' => 'Manapla', 'province_id' => 38],
            ['name' => 'Moises Padilla (Magallon)', 'province_id' => 38],
            ['name' => 'Murcia', 'province_id' => 38],
            ['name' => 'Pontevedra', 'province_id' => 38],
            ['name' => 'Pulupandan', 'province_id' => 38],
            ['name' => 'Sagay City', 'province_id' => 38],
            ['name' => 'San Carlos City', 'province_id' => 38],
            ['name' => 'San Enrique', 'province_id' => 38],
            ['name' => 'Silay City', 'province_id' => 38],
            ['name' => 'Sipalay City', 'province_id' => 38],
            ['name' => 'Talisay City', 'province_id' => 38],
            ['name' => 'Victorias City', 'province_id' => 38],
            ['name' => 'Valladolid', 'province_id' => 38],
            ['name' => 'La Carlota City', 'province_id' => 38],
            ['name' => 'Don Salvador Benedicto', 'province_id' => 38],
            ['name' => 'Toboso', 'province_id' => 38],

            // Bohol
            ['name' => 'Alburquerque', 'province_id' => 39],
            ['name' => 'Antequera', 'province_id' => 39],
            ['name' => 'Baclayon', 'province_id' => 39],
            ['name' => 'Balilihan', 'province_id' => 39],
            ['name' => 'Batuan (Bohol)', 'province_id' => 39],
            ['name' => 'Bilar', 'province_id' => 39],
            ['name' => 'Carmen (Bohol)', 'province_id' => 39],
            ['name' => 'Catigbian', 'province_id' => 39],
            ['name' => 'Clarin (Bohol)', 'province_id' => 39],
            ['name' => 'Corella', 'province_id' => 39],
            ['name' => 'Cortes (Bohol)', 'province_id' => 39],
            ['name' => 'Danao City (Bohol)', 'province_id' => 39],
            ['name' => 'Dimiao', 'province_id' => 39],
            ['name' => 'Duero', 'province_id' => 39],
            ['name' => 'Garcia Hernandez', 'province_id' => 39],
            ['name' => 'Getafe (Jetafe)', 'province_id' => 39],
            ['name' => 'Guindulman', 'province_id' => 39],
            ['name' => 'Inabanga', 'province_id' => 39],
            ['name' => 'Jagna', 'province_id' => 39],
            ['name' => 'Lila (Lila, Bohol)', 'province_id' => 39],
            ['name' => 'Loay (Loay, Bohol)', 'province_id' => 39],
            ['name' => 'Loon (Loon, Bohol)', 'province_id' => 39],
            ['name' => 'Mabini (Mabini, Bohol)', 'province_id' => 39],
            ['name' => 'Maribojoc', 'province_id' => 39],
            ['name' => 'Panglao', 'province_id' => 39],
            ['name' => 'Pilar (Bohol)', 'province_id' => 39],
            ['name' => 'Pres. Carlos P. Garcia (Pitogo)', 'province_id' => 39],
            ['name' => 'Sagbayan', 'province_id' => 39],
            ['name' => 'San Isidro (Bohol)', 'province_id' => 39],
            ['name' => 'San Miguel (Bohol)', 'province_id' => 39],
            ['name' => 'Sevilla', 'province_id' => 39],
            ['name' => 'Sierra Bullones', 'province_id' => 39],
            ['name' => 'Tagbilaran City (Capital)', 'province_id' => 39],
            ['name' => 'Talibon', 'province_id' => 39],
            ['name' => 'Trinidad (Bohol)', 'province_id' => 39],
            ['name' => 'Tubigon', 'province_id' => 39],
            ['name' => 'Ubay', 'province_id' => 39],
            ['name' => 'Valencia (Bohol)', 'province_id' => 39],
            ['name' => 'Bien Unido', 'province_id' => 39],
            ['name' => 'Sikatuna', 'province_id' => 39],
            ['name' => 'Dauis', 'province_id' => 39],

            // Cebu
            ['name' => 'Alcantara', 'province_id' => 40],
            ['name' => 'Alcoy', 'province_id' => 40],
            ['name' => 'Alegria', 'province_id' => 40],
            ['name' => 'Aloguinsan', 'province_id' => 40],
            ['name' => 'Argao', 'province_id' => 40],
            ['name' => 'Asturias', 'province_id' => 40],
            ['name' => 'Badian', 'province_id' => 40],
            ['name' => 'Balamban', 'province_id' => 40],
            ['name' => 'Bantayan', 'province_id' => 40],
            ['name' => 'Barili', 'province_id' => 40],
            ['name' => 'Boljoon', 'province_id' => 40],
            ['name' => 'Borbon', 'province_id' => 40],
            ['name' => 'Carcar City', 'province_id' => 40],
            ['name' => 'Carmen', 'province_id' => 40],
            ['name' => 'Catmon', 'province_id' => 40],
            ['name' => 'Cebu City (Capital)', 'province_id' => 40],
            ['name' => 'Compostela', 'province_id' => 40],
            ['name' => 'Consolacion', 'province_id' => 40],
            ['name' => 'Cordova', 'province_id' => 40],
            ['name' => 'Daanbantayan', 'province_id' => 40],
            ['name' => 'Dalaguete', 'province_id' => 40],
            ['name' => 'Dumanjug', 'province_id' => 40],
            ['name' => 'Ginatilan', 'province_id' => 40],
            ['name' => 'Lapu-Lapu City', 'province_id' => 40],
            ['name' => 'Liloan', 'province_id' => 40],
            ['name' => 'Madridejos', 'province_id' => 40],
            ['name' => 'Malabuyoc', 'province_id' => 40],
            ['name' => 'Mandaue City', 'province_id' => 40],
            ['name' => 'Medellin', 'province_id' => 40],
            ['name' => 'Minglanilla', 'province_id' => 40],
            ['name' => 'Moalboal', 'province_id' => 40],
            ['name' => 'Oslob', 'province_id' => 40],
            ['name' => 'Pilar (Cebu)', 'province_id' => 40],
            ['name' => 'Pinamungajan', 'province_id' => 40],
            ['name' => 'Porojan', 'province_id' => 40],
            ['name' => 'Ronda', 'province_id' => 40],
            ['name' => 'Samboan', 'province_id' => 40],
            ['name' => 'San Fernando (Cebu)', 'province_id' => 40],
            ['name' => 'San Francisco (Cebu)', 'province_id' => 40],
            ['name' => 'San Remigio', 'province_id' => 40],
            ['name' => 'Santa Fe', 'province_id' => 40],
            ['name' => 'Santander', 'province_id' => 40],
            ['name' => 'Sibonga', 'province_id' => 40],
            ['name' => 'Sogod', 'province_id' => 40],
            ['name' => 'Tabogon', 'province_id' => 40],
            ['name' => 'Tabuelan', 'province_id' => 40],
            ['name' => 'Talisay City (Cebu)', 'province_id' => 40],
            ['name' => 'Toledo City', 'province_id' => 40],
            ['name' => 'Tuburan', 'province_id' => 40],
            ['name' => 'Tudela', 'province_id' => 40],

            // Negros Oriental
            ['name' => 'Amlan', 'province_id' => 41],
            ['name' => 'Ayungon', 'province_id' => 41],
            ['name' => 'Bacong', 'province_id' => 41],
            ['name' => 'Basay', 'province_id' => 41],
            ['name' => 'Bayawan City', 'province_id' => 41],
            ['name' => 'Bindoy', 'province_id' => 41],
            ['name' => 'Dauin', 'province_id' => 41],
            ['name' => 'Dumaguete City (Capital)', 'province_id' => 41],
            ['name' => 'Guihulngan City', 'province_id' => 41],
            ['name' => 'Jimalalud', 'province_id' => 41],
            ['name' => 'La Libertad', 'province_id' => 41],
            ['name' => 'Mabinay', 'province_id' => 41],
            ['name' => 'Manjuyod', 'province_id' => 41],
            ['name' => 'Pamplona', 'province_id' => 41],
            ['name' => 'San Jose', 'province_id' => 41],
            ['name' => 'Santa Catalina', 'province_id' => 41],
            ['name' => 'Siaton', 'province_id' => 41],
            ['name' => 'Sibulan', 'province_id' => 41],
            ['name' => 'Tanjay City', 'province_id' => 41],
            ['name' => 'Tayasan', 'province_id' => 41],
            ['name' => 'Valencia', 'province_id' => 41],
            ['name' => 'Zamboanguita', 'province_id' => 41],

            // Siquijor
            ['name' => 'Enrique Villanueva', 'province_id' => 42],
            ['name' => 'Larena', 'province_id' => 42],
            ['name' => 'Lazi', 'province_id' => 42],
            ['name' => 'Maria', 'province_id' => 42],
            ['name' => 'San Juan', 'province_id' => 42],

            // Biliran
            ['name' => 'Almeria', 'province_id' => 43],
            ['name' => 'Biliran', 'province_id' => 43],
            ['name' => 'Cabucgayan', 'province_id' => 43],
            ['name' => 'Caibiran', 'province_id' => 43],
            ['name' => 'Culaba', 'province_id' => 43],
            ['name' => 'Kawayan', 'province_id' => 43],
            ['name' => 'Maripipi', 'province_id' => 43],
            ['name' => 'Naval (Capital)', 'province_id' => 43],

            // Eastern Samar
            ['name' => 'Arteche', 'province_id' => 44],
            ['name' => 'Balangiga', 'province_id' => 44],
            ['name' => 'Balangkayan', 'province_id' => 44],
            ['name' => 'Borongan (Capital)', 'province_id' => 44],
            ['name' => 'Can-avid', 'province_id' => 44],
            ['name' => 'Dolores', 'province_id' => 44],
            ['name' => 'General MacArthur', 'province_id' => 44],
            ['name' => 'Giporlos', 'province_id' => 44],
            ['name' => 'Llorente', 'province_id' => 44],
            ['name' => 'Maslog', 'province_id' => 44],
            ['name' => 'Maydolong', 'province_id' => 44],
            ['name' => 'Mercedes', 'province_id' => 44],
            ['name' => 'Oras', 'province_id' => 44],
            ['name' => 'San Julian', 'province_id' => 44],
            ['name' => 'San Policarpo', 'province_id' => 44],
            ['name' => 'Sulat', 'province_id' => 44],
            ['name' => 'Taft', 'province_id' => 44],

            // Leyte
            ['name' => 'Abuyog', 'province_id' => 45],
            ['name' => 'Alangalang', 'province_id' => 45],
            ['name' => 'Albuera', 'province_id' => 45],
            ['name' => 'Babatngon', 'province_id' => 45],
            ['name' => 'Barugo', 'province_id' => 45],
            ['name' => 'Bato', 'province_id' => 45],
            ['name' => 'Baybay City', 'province_id' => 45],
            ['name' => 'Burauen', 'province_id' => 45],
            ['name' => 'Calubian', 'province_id' => 45],
            ['name' => 'Capoocan', 'province_id' => 45],
            ['name' => 'Carigara', 'province_id' => 45],
            ['name' => 'Dagami', 'province_id' => 45],
            ['name' => 'Dulag', 'province_id' => 45],
            ['name' => 'Hilongos', 'province_id' => 45],
            ['name' => 'Hindang', 'province_id' => 45],
            ['name' => 'Inopacan', 'province_id' => 45],
            ['name' => 'Isabel', 'province_id' => 45],
            ['name' => 'Jaro', 'province_id' => 45],
            ['name' => 'Javier', 'province_id' => 45],
            ['name' => 'Kananga', 'province_id' => 45],
            ['name' => 'La Paz', 'province_id' => 45],
            ['name' => 'Leyte', 'province_id' => 45],
            ['name' => 'Macarthur', 'province_id' => 45],
            ['name' => 'Mahaplag', 'province_id' => 45],
            ['name' => 'Matag-ob', 'province_id' => 45],
            ['name' => 'Matalom', 'province_id' => 45],
            ['name' => 'Mayorga', 'province_id' => 45],
            ['name' => 'Merida', 'province_id' => 45],
            ['name' => 'Ormoc City', 'province_id' => 45],
            ['name' => 'Palo', 'province_id' => 45],
            ['name' => 'Palompon', 'province_id' => 45],
            ['name' => 'Pastrana', 'province_id' => 45],
            ['name' => 'San Isidro', 'province_id' => 45],
            ['name' => 'San Miguel', 'province_id' => 45],
            ['name' => 'Santa Fe', 'province_id' => 45],
            ['name' => 'Tabango', 'province_id' => 45],
            ['name' => 'Tabontabon', 'province_id' => 45],
            ['name' => 'Tacloban City (Capital)', 'province_id' => 45],
            ['name' => 'Tanauan', 'province_id' => 45],
            ['name' => 'Tolosa', 'province_id' => 45],
            ['name' => 'Tunga', 'province_id' => 45],
            ['name' => 'Villaba', 'province_id' => 45],

            // Northern Samar
            ['name' => 'Allen', 'province_id' => 46],
            ['name' => 'Biri', 'province_id' => 46],
            ['name' => 'Bobon', 'province_id' => 46],
            ['name' => 'Capul', 'province_id' => 46],
            ['name' => 'Catarman (Capital)', 'province_id' => 46],
            ['name' => 'Catubig', 'province_id' => 46],
            ['name' => 'Gamay', 'province_id' => 46],
            ['name' => 'Laoang', 'province_id' => 46],
            ['name' => 'Lapinig', 'province_id' => 46],
            ['name' => 'Las Navas', 'province_id' => 46],
            ['name' => 'Lavezares', 'province_id' => 46],
            ['name' => 'Mapanas', 'province_id' => 46],
            ['name' => 'Mondragon', 'province_id' => 46],
            ['name' => 'Palapag', 'province_id' => 46],
            ['name' => 'Pambujan', 'province_id' => 46],
            ['name' => 'Rosario', 'province_id' => 46],
            ['name' => 'San Antonio', 'province_id' => 46],
            ['name' => 'San Isidro', 'province_id' => 46],
            ['name' => 'San Jose', 'province_id' => 46],
            ['name' => 'San Roque', 'province_id' => 46],
            ['name' => 'San Vicente', 'province_id' => 46],
            ['name' => 'Silvino Lobos', 'province_id' => 46],

            // Samar (Western Samar)
            ['name' => 'Almagro', 'province_id' => 47],
            ['name' => 'Basey', 'province_id' => 47],
            ['name' => 'Calbiga', 'province_id' => 47],
            ['name' => 'Calbayog City', 'province_id' => 47],
            ['name' => 'Daram', 'province_id' => 47],
            ['name' => 'Gandara', 'province_id' => 47],
            ['name' => 'Hinabangan', 'province_id' => 47],
            ['name' => 'Jiabong', 'province_id' => 47],
            ['name' => 'Marabut', 'province_id' => 47],
            ['name' => 'Matuguinao', 'province_id' => 47],
            ['name' => 'Motiong', 'province_id' => 47],
            ['name' => 'Pinabacdao', 'province_id' => 47],
            ['name' => 'San Jorge', 'province_id' => 47],
            ['name' => 'San Jose de Buan', 'province_id' => 47],
            ['name' => 'San Sebastian', 'province_id' => 47],
            ['name' => 'Santa Margarita', 'province_id' => 47],
            ['name' => 'Santa Rita', 'province_id' => 47],
            ['name' => 'Santo Niño', 'province_id' => 47],
            ['name' => 'Tagapul-an', 'province_id' => 47],
            ['name' => 'Talalora', 'province_id' => 47],
            ['name' => 'Tarangnan', 'province_id' => 47],
            ['name' => 'Villareal', 'province_id' => 47],
            ['name' => 'Zumarraga', 'province_id' => 47],

            // Southern Leyte
            ['name' => 'Anahawan', 'province_id' => 48],
            ['name' => 'Bontoc', 'province_id' => 48],
            ['name' => 'Hinunangan', 'province_id' => 48],
            ['name' => 'Hinundayan', 'province_id' => 48],
            ['name' => 'Libagon', 'province_id' => 48],
            ['name' => 'Liloan', 'province_id' => 48],
            ['name' => 'Limasawa', 'province_id' => 48],
            ['name' => 'Maasin City (Capital)', 'province_id' => 48],
            ['name' => 'Macrohon', 'province_id' => 48],
            ['name' => 'Malitbog', 'province_id' => 48],
            ['name' => 'Padre Burgos', 'province_id' => 48],
            ['name' => 'Pintuyan', 'province_id' => 48],
            ['name' => 'Saint Bernard', 'province_id' => 48],
            ['name' => 'San Francisco', 'province_id' => 48],
            ['name' => 'San Juan (Southern Leyte)', 'province_id' => 48],
            ['name' => 'San Ricardo', 'province_id' => 48],
            ['name' => 'Silago', 'province_id' => 48],
            ['name' => 'Sogod', 'province_id' => 48],
            ['name' => 'Tomas Oppus', 'province_id' => 48],

            // Zamboanga City
            // ['name' => 'Zamboanga City (Highly Urbanized City)', 'province_id' => 49],

            // Zamboanga del Norte
            ['name' => 'Baliguian', 'province_id' => 49],
            ['name' => 'Dapitan City', 'province_id' => 49],
            ['name' => 'Dipolog City (Capital)', 'province_id' => 49],
            ['name' => 'Godod', 'province_id' => 49],
            ['name' => 'Gutalac', 'province_id' => 49],
            ['name' => 'Jose Dalman', 'province_id' => 49],
            ['name' => 'Kalawit', 'province_id' => 49],
            ['name' => 'Katipunan', 'province_id' => 49],
            ['name' => 'La Libertad', 'province_id' => 49],
            ['name' => 'Labason', 'province_id' => 49],
            ['name' => 'Liloy', 'province_id' => 49],
            ['name' => 'Manukan', 'province_id' => 49],
            ['name' => 'Mutia', 'province_id' => 49],
            ['name' => 'Piñan', 'province_id' => 49],
            ['name' => 'Polanco', 'province_id' => 49],
            ['name' => 'Rizal', 'province_id' => 49],
            ['name' => 'Salug', 'province_id' => 49],
            ['name' => 'Sergio Osmeña Sr.', 'province_id' => 49],
            ['name' => 'Siayan', 'province_id' => 49],
            ['name' => 'Sibuco', 'province_id' => 49],
            ['name' => 'Sibutad', 'province_id' => 49],
            ['name' => 'Sindangan', 'province_id' => 49],
            ['name' => 'Siocon', 'province_id' => 49],
            ['name' => 'Sirawai', 'province_id' => 49],
            ['name' => 'Tampilisan', 'province_id' => 49],

            // Zamboanga del Sur
            ['name' => 'Bayog', 'province_id' => 50],
            ['name' => 'Dimataling', 'province_id' => 50],
            ['name' => 'Dinas', 'province_id' => 50],
            ['name' => 'Dumalinao', 'province_id' => 50],
            ['name' => 'Dumingag', 'province_id' => 50],
            ['name' => 'Guipos', 'province_id' => 50],
            ['name' => 'Josefina', 'province_id' => 50],
            ['name' => 'Kumalarang', 'province_id' => 50],
            ['name' => 'Labangan', 'province_id' => 50],
            ['name' => 'Lakewood', 'province_id' => 50],
            ['name' => 'Lapuyan', 'province_id' => 50],
            ['name' => 'Mahayag', 'province_id' => 50],
            ['name' => 'Margosatubig', 'province_id' => 50],
            ['name' => 'Midsalip', 'province_id' => 50],
            ['name' => 'Molave', 'province_id' => 50],
            ['name' => 'Pagadian City (Capital)', 'province_id' => 50],
            ['name' => 'Pitogo', 'province_id' => 50],
            ['name' => 'Ramon Magsaysay', 'province_id' => 50],
            ['name' => 'San Miguel', 'province_id' => 50],
            ['name' => 'San Pablo', 'province_id' => 50],
            ['name' => 'Sominot', 'province_id' => 50],
            ['name' => 'Tabina', 'province_id' => 50],
            ['name' => 'Tambulig', 'province_id' => 50],
            ['name' => 'Tigbao', 'province_id' => 50],
            ['name' => 'Titay', 'province_id' => 50],
            ['name' => 'Tukuran', 'province_id' => 50],
            ['name' => 'Zamboanga City', 'province_id' => 50],

            // Zamboanga Sibugay
            ['name' => 'Alicia', 'province_id' => 51],
            ['name' => 'Buug', 'province_id' => 51],
            ['name' => 'Diplahan', 'province_id' => 51],
            ['name' => 'Imelda', 'province_id' => 51],
            ['name' => 'Ipil (Capital)', 'province_id' => 51],
            ['name' => 'Kabasalan', 'province_id' => 51],
            ['name' => 'Mabuhay', 'province_id' => 51],
            ['name' => 'Malangas', 'province_id' => 51],
            ['name' => 'Naga', 'province_id' => 51],
            ['name' => 'Olutanga', 'province_id' => 51],
            ['name' => 'Payao', 'province_id' => 51],
            ['name' => 'Roseller Lim', 'province_id' => 51],
            ['name' => 'Siay', 'province_id' => 51],
            ['name' => 'Talusan', 'province_id' => 51],
            ['name' => 'Titay', 'province_id' => 51],
            ['name' => 'Tungawan', 'province_id' => 51],

            // Bukidnon
            ['name' => 'Baungon', 'province_id' => 52],
            ['name' => 'Cabanglasan', 'province_id' => 52],
            ['name' => 'Damulog', 'province_id' => 52],
            ['name' => 'Dangcagan', 'province_id' => 52],
            ['name' => 'Don Carlos', 'province_id' => 52],
            ['name' => 'Impasugong', 'province_id' => 52],
            ['name' => 'Kadingilan', 'province_id' => 52],
            ['name' => 'Kalilangan', 'province_id' => 52],
            ['name' => 'Kibawe', 'province_id' => 52],
            ['name' => 'Kitaotao', 'province_id' => 52],
            ['name' => 'Lantapan', 'province_id' => 52],
            ['name' => 'Libona', 'province_id' => 52],
            ['name' => 'Malaybalay City (Capital)', 'province_id' => 52],
            ['name' => 'Malitbog', 'province_id' => 52],
            ['name' => 'Manolo Fortich', 'province_id' => 52],
            ['name' => 'Maramag', 'province_id' => 52],
            ['name' => 'Pangantucan', 'province_id' => 52],
            ['name' => 'Quezon (Bukidnon)', 'province_id' => 52],
            ['name' => 'San Fernando (Bukidnon)', 'province_id' => 52],
            ['name' => 'Sumilao', 'province_id' => 52],
            ['name' => 'Talakag', 'province_id' => 52],
            ['name' => 'Valencia City', 'province_id' => 52],


            // Camiguin
            ['name' => 'Catarman (Camiguin)', 'province_id' => 53],
            ['name' => 'Guinsiliban', 'province_id' => 53],
            ['name' => 'Mahinog', 'province_id' => 53],
            ['name' => 'Mambajao (Capital)', 'province_id' => 53],
            ['name' => 'Sagay (Camiguin)', 'province_id' => 53],


            // Lanao del Norte
            ['name' => 'Bacolod (Lanao del Norte)', 'province_id' => 54],
            ['name' => 'Baloi', 'province_id' => 54],
            ['name' => 'Baroy', 'province_id' => 54],
            ['name' => 'Iligan City', 'province_id' => 54],
            ['name' => 'Kapatagan', 'province_id' => 54],
            ['name' => 'Kauswagan', 'province_id' => 54],
            ['name' => 'Kolambugan', 'province_id' => 54],
            ['name' => 'Lala', 'province_id' => 54],
            ['name' => 'Linamon', 'province_id' => 54],
            ['name' => 'Magsaysay (Lanao del Norte)', 'province_id' => 54],
            ['name' => 'Maigo', 'province_id' => 54],
            ['name' => 'Matungao', 'province_id' => 54],
            ['name' => 'Munai', 'province_id' => 54],
            ['name' => 'Nunungan', 'province_id' => 54],
            ['name' => 'Pantao Ragat', 'province_id' => 54],
            ['name' => 'Pantar', 'province_id' => 54],
            ['name' => 'Poona Piagapo', 'province_id' => 54],
            ['name' => 'Salvador', 'province_id' => 54],
            ['name' => 'Sapad', 'province_id' => 54],
            ['name' => 'Sultan Naga Dimaporo', 'province_id' => 54],
            ['name' => 'Tagoloan (Lanao del Norte)', 'province_id' => 54],
            ['name' => 'Tangcal', 'province_id' => 54],
            ['name' => 'Tubod (Capital)', 'province_id' => 54],


            // Misamis Occidental
            ['name' => 'Aloran', 'province_id' => 55],
            ['name' => 'Baliangao', 'province_id' => 55],
            ['name' => 'Bonifacio', 'province_id' => 55],
            ['name' => 'Calamba (Misamis Occidental)', 'province_id' => 55],
            ['name' => 'Clarin (Misamis Occidental)', 'province_id' => 55],
            ['name' => 'Concepcion (Misamis Occidental)', 'province_id' => 55],
            ['name' => 'Don Victoriano Chiongbian', 'province_id' => 55],
            ['name' => 'Jimenez', 'province_id' => 55],
            ['name' => 'Lopez Jaena (Misamis Occidental)', 'province_id' => 55],
            ['name' => 'Oroquieta City (Capital)', 'province_id' => 55],
            ['name' => 'Ozamiz City', 'province_id' => 55],
            ['name' => 'Panaon', 'province_id' => 55],
            ['name' => 'Plaridel (Misamis Occidental)', 'province_id' => 55],
            ['name' => 'Sapang Dalaga', 'province_id' => 55],
            ['name' => 'Sinacaban', 'province_id' => 55],
            ['name' => 'Tangub City', 'province_id' => 55],
            ['name' => 'Tudela (Misamis Occidental)', 'province_id' => 55],


            // Misamis Oriental
            ['name' => 'Alubijid', 'province_id' => 56],
            ['name' => 'Balingasag', 'province_id' => 56],
            ['name' => 'Balingoan', 'province_id' => 56],
            ['name' => 'Binuangan', 'province_id' => 56],
            ['name' => 'Cagayan de Oro City (Capital)', 'province_id' => 56],
            ['name' => 'Claveria (Misamis Oriental)', 'province_id' => 56],
            ['name' => 'El Salvador City', 'province_id' => 56],
            ['name' => 'Gingoog City', 'province_id' => 56],
            ['name' => 'Gitagum', 'province_id' => 56],
            ['name' => 'Initao', 'province_id' => 56],
            ['name' => 'Jasaan', 'province_id' => 56],
            ['name' => 'Kinoguitan', 'province_id' => 56],
            ['name' => 'Lagonglong', 'province_id' => 56],
            ['name' => 'Laguindingan', 'province_id' => 56],
            ['name' => 'Libertad (Misamis Oriental)', 'province_id' => 56],
            ['name' => 'Lugait', 'province_id' => 56],
            ['name' => 'Magsaysay (Misamis Oriental)', 'province_id' => 56],
            ['name' => 'Manticao', 'province_id' => 56],
            ['name' => 'Medina (Misamis Oriental)', 'province_id' => 56],
            ['name' => 'Naawan', 'province_id' => 56],
            ['name' => 'Opol', 'province_id' => 56],
            ['name' => 'Salay', 'province_id' => 56],
            ['name' => 'Sugbongcogon', 'province_id' => 56],
            ['name' => 'Tagoloan (Misamis Oriental)', 'province_id' => 56],
            ['name' => 'Talisayan (Misamis Oriental)', 'province_id' => 56],
            ['name' => 'Villanueva', 'province_id' => 56],

            // Davao de Oro (Compostela Valley)
            ['name' => 'Compostela', 'province_id' => 57],
            ['name' => 'Laak (San Vicente)', 'province_id' => 57],
            ['name' => 'Mabini (Davao de Oro)', 'province_id' => 57],
            ['name' => 'Maco', 'province_id' => 57],
            ['name' => 'Maragusan (San Mariano)', 'province_id' => 57],
            ['name' => 'Mawab', 'province_id' => 57],
            ['name' => 'Monkayo', 'province_id' => 57],
            ['name' => 'Montevista', 'province_id' => 57],
            ['name' => 'Nabunturan (Capital)', 'province_id' => 57],
            ['name' => 'New Bataan', 'province_id' => 57],
            ['name' => 'Pantukan', 'province_id' => 57],


            // Davao del Norte
            ['name' => 'Asuncion (Saug)', 'province_id' => 58],
            ['name' => 'Braulio E. Dujali', 'province_id' => 58],
            ['name' => 'Carmen (Davao del Norte)', 'province_id' => 58],
            ['name' => 'Kapalong', 'province_id' => 58],
            ['name' => 'New Corella', 'province_id' => 58],
            ['name' => 'Panabo City', 'province_id' => 58],
            ['name' => 'Samal City (Island Garden City of Samal)', 'province_id' => 58],
            ['name' => 'San Isidro (Davao del Norte)', 'province_id' => 58],
            ['name' => 'Santo Tomas (Davao del Norte)', 'province_id' => 58],
            ['name' => 'Tagum City (Capital)', 'province_id' => 58],
            ['name' => 'Talaingod', 'province_id' => 58],


            // Davao del Sur
            ['name' => 'Bansalan', 'province_id' => 59],
            ['name' => 'Davao City', 'province_id' => 59],
            ['name' => 'Digos City (Capital)', 'province_id' => 59],
            ['name' => 'Hagonoy (Davao del Sur)', 'province_id' => 59],
            ['name' => 'Kiblawan', 'province_id' => 59],
            ['name' => 'Magsaysay (Davao del Sur)', 'province_id' => 59],
            ['name' => 'Malalag', 'province_id' => 59],
            ['name' => 'Matanao', 'province_id' => 59],
            ['name' => 'Padada', 'province_id' => 59],
            ['name' => 'Santa Cruz (Davao del Sur)', 'province_id' => 59],
            ['name' => 'Sulop', 'province_id' => 59],


            // Davao Occidental
            ['name' => 'Don Marcelino', 'province_id' => 60],
            ['name' => 'Jose Abad Santos', 'province_id' => 60],
            ['name' => 'Malita (Capital)', 'province_id' => 60],
            ['name' => 'Santa Maria (Davao Occidental)', 'province_id' => 60],
            ['name' => 'Sarangani (Davao Occidental)', 'province_id' => 60],


            // Davao Oriental
            ['name' => 'Baganga', 'province_id' => 61],
            ['name' => 'Banaybanay', 'province_id' => 61],
            ['name' => 'Boston', 'province_id' => 61],
            ['name' => 'Caraga (Davao Oriental)', 'province_id' => 61],
            ['name' => 'Cateel', 'province_id' => 61],
            ['name' => 'Governor Generoso', 'province_id' => 61],
            ['name' => 'Lupon', 'province_id' => 61],
            ['name' => 'Manay', 'province_id' => 61],
            ['name' => 'Mati City (Capital)', 'province_id' => 61],
            ['name' => 'San Isidro (Davao Oriental)', 'province_id' => 61],
            ['name' => 'Tarragona', 'province_id' => 61],

            // Cotabato (North Cotabato)
            ['name' => 'Alamada', 'province_id' => 62],
            ['name' => 'Aleosan', 'province_id' => 62],
            ['name' => 'Antipas', 'province_id' => 62],
            ['name' => 'Arakan', 'province_id' => 62],
            ['name' => 'Banisilan', 'province_id' => 62],
            ['name' => 'Carmen (Cotabato)', 'province_id' => 62],
            ['name' => 'Kabacan', 'province_id' => 62],
            ['name' => 'Kidapawan City (Capital)', 'province_id' => 62],
            ['name' => 'Libungan', 'province_id' => 62],
            ['name' => 'Magpet', 'province_id' => 62],
            ['name' => 'Makilala', 'province_id' => 62],
            ['name' => 'Matalam', 'province_id' => 62],
            ['name' => 'Midsayap', 'province_id' => 62],
            ['name' => 'Pigcawayan', 'province_id' => 62],
            ['name' => 'Pikit', 'province_id' => 62],
            ['name' => 'President Roxas', 'province_id' => 62],
            ['name' => 'Tulunan', 'province_id' => 62],


            // Sarangani
            ['name' => 'Alabel (Capital)', 'province_id' => 63],
            ['name' => 'Glan', 'province_id' => 63],
            ['name' => 'Kiamba', 'province_id' => 63],
            ['name' => 'Maasim', 'province_id' => 63],
            ['name' => 'Maitum', 'province_id' => 63],
            ['name' => 'Malapatan', 'province_id' => 63],
            ['name' => 'Malungon', 'province_id' => 63],


            // South Cotabato
            ['name' => 'Banga', 'province_id' => 64],
            ['name' => 'General Santos City (Dadiangas)', 'province_id' => 64],
            ['name' => 'Koronadal City (Capital)', 'province_id' => 64],
            ['name' => 'Lake Sebu', 'province_id' => 64],
            ['name' => 'Norala', 'province_id' => 64],
            ['name' => 'Polomolok', 'province_id' => 64],
            ['name' => 'Santo Niño (South Cotabato)', 'province_id' => 64],
            ['name' => 'Surallah', 'province_id' => 64],
            ['name' => 'Tampakan', 'province_id' => 64],
            ['name' => 'Tantangan', 'province_id' => 64],
            ['name' => 'Tupi', 'province_id' => 64],


            // Sultan Kudarat
            ['name' => 'Bagumbayan', 'province_id' => 65],
            ['name' => 'Columbio', 'province_id' => 65],
            ['name' => 'Esperanza (Sultan Kudarat)', 'province_id' => 65],
            ['name' => 'Isulan (Capital)', 'province_id' => 65],
            ['name' => 'Kalamansig', 'province_id' => 65],
            ['name' => 'Lambayong', 'province_id' => 65],
            ['name' => 'Lebak', 'province_id' => 65],
            ['name' => 'Lutayan', 'province_id' => 65],
            ['name' => 'Palimbang', 'province_id' => 65],
            ['name' => 'President Quirino', 'province_id' => 65],
            ['name' => 'Sen. Ninoy Aquino', 'province_id' => 65],

            // Agusan del Norte
            ['name' => 'Buenavista (Agusan del Norte)', 'province_id' => 66],
            ['name' => 'Butuan City (Capital)', 'province_id' => 66],
            ['name' => 'Cabadbaran City', 'province_id' => 66],
            ['name' => 'Carmen (Agusan del Norte)', 'province_id' => 66],
            ['name' => 'Jabonga', 'province_id' => 66],
            ['name' => 'Kitcharao', 'province_id' => 66],
            ['name' => 'Las Nieves', 'province_id' => 66],
            ['name' => 'Magallanes (Agusan del Norte)', 'province_id' => 66],
            ['name' => 'Nasipit', 'province_id' => 66],
            ['name' => 'Remedios T. Romualdez', 'province_id' => 66],
            ['name' => 'Santiago (Agusan del Norte)', 'province_id' => 66],


            // Agusan del Sur
            ['name' => 'Bayugan City', 'province_id' => 67],
            ['name' => 'Bunawan', 'province_id' => 67],
            ['name' => 'Esperanza (Agusan del Sur)', 'province_id' => 67],
            ['name' => 'La Paz (Agusan del Sur)', 'province_id' => 67],
            ['name' => 'Loreto (Agusan del Sur)', 'province_id' => 67],
            ['name' => 'Prosperidad (Capital)', 'province_id' => 67],
            ['name' => 'Rosario (Agusan del Sur)', 'province_id' => 67],
            ['name' => 'San Francisco (Agusan del Sur)', 'province_id' => 67],
            ['name' => 'San Luis (Agusan del Sur)', 'province_id' => 67],
            ['name' => 'Santa Josefa', 'province_id' => 67],
            ['name' => 'Sibagat', 'province_id' => 67],
            ['name' => 'Talacogon', 'province_id' => 67],
            ['name' => 'Trento', 'province_id' => 67],


            // Dinagat Islands
            ['name' => 'Basilisa (Rizal)', 'province_id' => 68],
            ['name' => 'Cagdianao', 'province_id' => 68],
            ['name' => 'Dinagat', 'province_id' => 68],
            ['name' => 'Libjo (Albor)', 'province_id' => 68],
            ['name' => 'Loreto (Dinagat Islands)', 'province_id' => 68],
            ['name' => 'San Jose (Capital)', 'province_id' => 68],
            ['name' => 'Tubajon', 'province_id' => 68],


            // Surigao del Norte
            ['name' => 'Alegria (Surigao del Norte)', 'province_id' => 69],
            ['name' => 'Bacuag', 'province_id' => 69],
            ['name' => 'Burgos (Surigao del Norte)', 'province_id' => 69],
            ['name' => 'Claver', 'province_id' => 69],
            ['name' => 'Dapa', 'province_id' => 69],
            ['name' => 'Del Carmen', 'province_id' => 69],
            ['name' => 'General Luna', 'province_id' => 69],
            ['name' => 'Gigaquit', 'province_id' => 69],
            ['name' => 'Mainit', 'province_id' => 69],
            ['name' => 'Malimono', 'province_id' => 69],
            ['name' => 'Pilar (Surigao del Norte)', 'province_id' => 69],
            ['name' => 'Placer (Surigao del Norte)', 'province_id' => 69],
            ['name' => 'San Benito', 'province_id' => 69],
            ['name' => 'San Francisco (Anao-aon)', 'province_id' => 69],
            ['name' => 'San Isidro (Surigao del Norte)', 'province_id' => 69],
            ['name' => 'Santa Monica (Sapao)', 'province_id' => 69],
            ['name' => 'Sison (Surigao del Norte)', 'province_id' => 69],
            ['name' => 'Socorro (Surigao del Norte)', 'province_id' => 69],
            ['name' => 'Surigao City (Capital)', 'province_id' => 69],
            ['name' => 'Tagana-an', 'province_id' => 69],
            ['name' => 'Tubod (Surigao del Norte)', 'province_id' => 69],


            // Surigao del Sur
            ['name' => 'Barobo', 'province_id' => 70],
            ['name' => 'Bayabas', 'province_id' => 70],
            ['name' => 'Bislig City', 'province_id' => 70],
            ['name' => 'Cagwait', 'province_id' => 70],
            ['name' => 'Cantilan', 'province_id' => 70],
            ['name' => 'Carmen (Surigao del Sur)', 'province_id' => 70],
            ['name' => 'Carrascal', 'province_id' => 70],
            ['name' => 'Cortes (Surigao del Sur)', 'province_id' => 70],
            ['name' => 'Hinatuan', 'province_id' => 70],
            ['name' => 'Lanuza', 'province_id' => 70],
            ['name' => 'Lianga', 'province_id' => 70],
            ['name' => 'Lingig', 'province_id' => 70],
            ['name' => 'Madrid', 'province_id' => 70],
            ['name' => 'Marihatag', 'province_id' => 70],
            ['name' => 'San Agustin (Surigao del Sur)', 'province_id' => 70],
            ['name' => 'San Miguel (Surigao del Sur)', 'province_id' => 70],
            ['name' => 'Tagbina', 'province_id' => 70],
            ['name' => 'Tago', 'province_id' => 70],
            ['name' => 'Tandag City (Capital)', 'province_id' => 70],

            // Metro Manila (NCR)
            ['name' => 'Caloocan', 'province_id' => 71],
            ['name' => 'Las Piñas', 'province_id' => 72],
            ['name' => 'Makati', 'province_id' => 73],
            ['name' => 'Malabon', 'province_id' => 74],
            ['name' => 'Mandaluyong', 'province_id' => 75],
            ['name' => 'Manila', 'province_id' => 76],
            ['name' => 'Marikina', 'province_id' => 77],
            ['name' => 'Muntinlupa', 'province_id' => 78],
            ['name' => 'Navotas', 'province_id' => 79],
            ['name' => 'Parañaque', 'province_id' => 80],
            ['name' => 'Pasay', 'province_id' => 81],
            ['name' => 'Pasig', 'province_id' => 82],
            ['name' => 'Quezon City', 'province_id' => 83],
            ['name' => 'San Juan', 'province_id' => 84],
            ['name' => 'Taguig', 'province_id' => 85],
            ['name' => 'Valenzuela', 'province_id' => 86],
            ['name' => 'Pateros', 'province_id' => 87],

            // Abra
            ['name' => 'Bangued (Capital)', 'province_id' => 88],
            ['name' => 'Boliney', 'province_id' => 88],
            ['name' => 'Bucay', 'province_id' => 88],
            ['name' => 'Bucloc', 'province_id' => 88],
            ['name' => 'Daguioman', 'province_id' => 88],
            ['name' => 'Danglas', 'province_id' => 88],
            ['name' => 'Dolores (Abra)', 'province_id' => 88],
            ['name' => 'La Paz (Abra)', 'province_id' => 88],
            ['name' => 'Lacub', 'province_id' => 88],
            ['name' => 'Lagangilang', 'province_id' => 88],
            ['name' => 'Lagayan', 'province_id' => 88],
            ['name' => 'Langiden', 'province_id' => 88],
            ['name' => 'Licuan-Baay', 'province_id' => 88],
            ['name' => 'Luba', 'province_id' => 88],
            ['name' => 'Malibcong', 'province_id' => 88],
            ['name' => 'Manabo', 'province_id' => 88],
            ['name' => 'Peñarrubia', 'province_id' => 88],
            ['name' => 'Pidigan', 'province_id' => 88],
            ['name' => 'Pilar (Abra)', 'province_id' => 88],
            ['name' => 'Sallapadan', 'province_id' => 88],
            ['name' => 'San Isidro (Abra)', 'province_id' => 88],
            ['name' => 'San Juan (Abra)', 'province_id' => 88],
            ['name' => 'San Quintin', 'province_id' => 88],
            ['name' => 'Tayum', 'province_id' => 88],
            ['name' => 'Tineg', 'province_id' => 88],
            ['name' => 'Tubo', 'province_id' => 88],
            ['name' => 'Villaviciosa', 'province_id' => 88],

            // Apayao
            ['name' => 'Calanasan (Bayag)', 'province_id' => 89],
            ['name' => 'Conner', 'province_id' => 89],
            ['name' => 'Flora', 'province_id' => 89],
            ['name' => 'Kabugao (Capital)', 'province_id' => 89],
            ['name' => 'Luna (Apayao)', 'province_id' => 89],
            ['name' => 'Pudtol', 'province_id' => 89],
            ['name' => 'Santa Marcela', 'province_id' => 89],

            // Benguet
            ['name' => 'Atok', 'province_id' => 90],
            ['name' => 'Bakun', 'province_id' => 90],
            ['name' => 'Bokod', 'province_id' => 90],
            ['name' => 'Buguias', 'province_id' => 90],
            ['name' => 'Itogon', 'province_id' => 90],
            ['name' => 'Kabayan', 'province_id' => 90],
            ['name' => 'Kapangan', 'province_id' => 90],
            ['name' => 'Kibungan', 'province_id' => 90],
            ['name' => 'La Trinidad (Capital)', 'province_id' => 90],
            ['name' => 'Mankayan', 'province_id' => 90],
            ['name' => 'Sablan', 'province_id' => 90],
            ['name' => 'Tuba', 'province_id' => 90],
            ['name' => 'Tublay', 'province_id' => 90],

            // Ifugao
            ['name' => 'Aguinaldo', 'province_id' => 91],
            ['name' => 'Alfonso Lista', 'province_id' => 91],
            ['name' => 'Asipulo', 'province_id' => 91],
            ['name' => 'Banaue', 'province_id' => 91],
            ['name' => 'Hingyon', 'province_id' => 91],
            ['name' => 'Hungduan', 'province_id' => 91],
            ['name' => 'Kiangan', 'province_id' => 91],
            ['name' => 'Lagawe (Capital)', 'province_id' => 91],
            ['name' => 'Lamut', 'province_id' => 91],
            ['name' => 'Mayoyao', 'province_id' => 91],
            ['name' => 'Tinoc', 'province_id' => 91],

            // Kalinga
            ['name' => 'Balbalan', 'province_id' => 92],
            ['name' => 'Lubuagan', 'province_id' => 92],
            ['name' => 'Pasil', 'province_id' => 92],
            ['name' => 'Pinukpuk', 'province_id' => 92],
            ['name' => 'Rizal (Kalinga)', 'province_id' => 92],
            ['name' => 'Tabuk City (Capital)', 'province_id' => 92],
            ['name' => 'Tanudan', 'province_id' => 92],
            ['name' => 'Tinglayan', 'province_id' => 92],

            // Mountain Province
            ['name' => 'Barlig', 'province_id' => 93],
            ['name' => 'Bauko', 'province_id' => 93],
            ['name' => 'Besao', 'province_id' => 93],
            ['name' => 'Bontoc (Capital)', 'province_id' => 93],
            ['name' => 'Natonin', 'province_id' => 93],
            ['name' => 'Paracelis', 'province_id' => 93],
            ['name' => 'Sabangan', 'province_id' => 93],
            ['name' => 'Sadanga', 'province_id' => 93],
            ['name' => 'Sagada', 'province_id' => 93],
            ['name' => 'Tadian', 'province_id' => 93],

            // Basilan
            ['name' => 'Isabela City', 'province_id' => 94],
            ['name' => 'Akbar', 'province_id' => 94],
            ['name' => 'Al-Barka', 'province_id' => 94],
            ['name' => 'Hadji Mohammad Ajul', 'province_id' => 94],
            ['name' => 'Hadji Muhtamad', 'province_id' => 94],
            ['name' => 'Lantawan', 'province_id' => 94],
            ['name' => 'Maluso', 'province_id' => 94],
            ['name' => 'Sumisip', 'province_id' => 94],
            ['name' => 'Tabuan-Lasa', 'province_id' => 94],
            ['name' => 'Tipo-Tipo', 'province_id' => 94],
            ['name' => 'Tuburan (Basilan)', 'province_id' => 94],
            ['name' => 'Ungkaya Pukan', 'province_id' => 94],

            // Lanao del Sur
            ['name' => 'Marawi City (Capital)', 'province_id' => 95],
            ['name' => 'Bacolod-Kalawi (Bacolod Grande)', 'province_id' => 95],
            ['name' => 'Balabagan', 'province_id' => 95],
            ['name' => 'Balindong (Watu)', 'province_id' => 95],
            ['name' => 'Bayang', 'province_id' => 95],
            ['name' => 'Binidayan', 'province_id' => 95],
            ['name' => 'Buadiposo-Buntong', 'province_id' => 95],
            ['name' => 'Bubong', 'province_id' => 95],
            ['name' => 'Butig', 'province_id' => 95],
            ['name' => 'Calanogas', 'province_id' => 95],
            ['name' => 'Ditsaan-Ramain', 'province_id' => 95],
            ['name' => 'Ganassi', 'province_id' => 95],
            ['name' => 'Kapai', 'province_id' => 95],
            ['name' => 'Kapatagan (Lanao del Sur)', 'province_id' => 95],
            ['name' => 'Lumba-Bayabao (Maguing)', 'province_id' => 95],
            ['name' => 'Lumbaca-Unayan', 'province_id' => 95],
            ['name' => 'Lumbatan', 'province_id' => 95],
            ['name' => 'Lumbayanague', 'province_id' => 95],
            ['name' => 'Madalum', 'province_id' => 95],
            ['name' => 'Madamba', 'province_id' => 95],
            ['name' => 'Maguing', 'province_id' => 95],
            ['name' => 'Malabang', 'province_id' => 95],
            ['name' => 'Marantao', 'province_id' => 95],
            ['name' => 'Marogong', 'province_id' => 95],
            ['name' => 'Masiu', 'province_id' => 95],
            ['name' => 'Mulondo', 'province_id' => 95],
            ['name' => 'Pagayawan (Tatarikan)', 'province_id' => 95],
            ['name' => 'Piagapo', 'province_id' => 95],
            ['name' => 'Poona Bayabao (Gata)', 'province_id' => 95],
            ['name' => 'Pualas', 'province_id' => 95],
            ['name' => 'Saguiaran', 'province_id' => 95],
            ['name' => 'Sultan Dumalondong', 'province_id' => 95],
            ['name' => 'Picong (Sultan Gumander)', 'province_id' => 95],
            ['name' => 'Tagoloan II', 'province_id' => 95],
            ['name' => 'Tamparan', 'province_id' => 95],
            ['name' => 'Taraka', 'province_id' => 95],
            ['name' => 'Tubaran', 'province_id' => 95],
            ['name' => 'Tugaya', 'province_id' => 95],
            ['name' => 'Wao', 'province_id' => 95],

            // Maguindanao del Norte
            ['name' => 'Barira', 'province_id' => 96],
            ['name' => 'Buldon', 'province_id' => 96],
            ['name' => 'Datu Blah T. Sinsuat', 'province_id' => 96],
            ['name' => 'Datu Odin Sinsuat (Dinaig)', 'province_id' => 96],
            ['name' => 'Kabuntalan (Tumbao)', 'province_id' => 96],
            ['name' => 'Matanog', 'province_id' => 96],
            ['name' => 'Northern Kabuntalan', 'province_id' => 96],
            ['name' => 'Parang', 'province_id' => 96],
            ['name' => 'Sultan Kudarat (Nuling)', 'province_id' => 96],
            ['name' => 'Sultan Mastura', 'province_id' => 96],
            ['name' => 'Upi', 'province_id' => 96],

            // Maguindanao del Sur
            ['name' => 'Ampatuan', 'province_id' => 97],
            ['name' => 'Buluan', 'province_id' => 97],
            ['name' => 'Datu Abdullah Sangki', 'province_id' => 97],
            ['name' => 'Datu Anggal Midtimbang', 'province_id' => 97],
            ['name' => 'Datu Hoffer Ampatuan', 'province_id' => 97],
            ['name' => 'Datu Paglas', 'province_id' => 97],
            ['name' => 'Datu Piang', 'province_id' => 97],
            ['name' => 'Datu Salibo', 'province_id' => 97],
            ['name' => 'Datu Saudi-Ampatuan', 'province_id' => 97],
            ['name' => 'Datu Unsay', 'province_id' => 97],
            ['name' => 'General Salipada K. Pendatun', 'province_id' => 97],
            ['name' => 'Guindulungan', 'province_id' => 97],
            ['name' => 'Mamasapano', 'province_id' => 97],
            ['name' => 'Mangudadatu', 'province_id' => 97],
            ['name' => 'Pagalungan', 'province_id' => 97],
            ['name' => 'Paglat', 'province_id' => 97],
            ['name' => 'Pandag', 'province_id' => 97],
            ['name' => 'Rajah Buayan', 'province_id' => 97],
            ['name' => 'Shariff Aguak (Maganoy)', 'province_id' => 97],
            ['name' => 'Shariff Saydona Mustapha', 'province_id' => 97],
            ['name' => 'South Upi', 'province_id' => 97],
            ['name' => 'Sultan sa Barongis (Lambayong)', 'province_id' => 97],
            ['name' => 'Talayan', 'province_id' => 97],
            ['name' => 'Talitay', 'province_id' => 97],

            // Sulu
            ['name' => 'Banguingui (Tongi)', 'province_id' => 98],
            ['name' => 'Hadji Panglima Tahil (Marunggas)', 'province_id' => 98],
            ['name' => 'Indanan', 'province_id' => 98],
            ['name' => 'Jolo (Capital)', 'province_id' => 98],
            ['name' => 'Kalingalan Caluang', 'province_id' => 98],
            ['name' => 'Lugus', 'province_id' => 98],
            ['name' => 'Luuk', 'province_id' => 98],
            ['name' => 'Maimbung', 'province_id' => 98],
            ['name' => 'Old Panamao', 'province_id' => 98],
            ['name' => 'Omar', 'province_id' => 98],
            ['name' => 'Pandami', 'province_id' => 98],
            ['name' => 'Panglima Estino (New Panamao)', 'province_id' => 98],
            ['name' => 'Pangutaran', 'province_id' => 98],
            ['name' => 'Parang (Sulu)', 'province_id' => 98],
            ['name' => 'Pata', 'province_id' => 98],
            ['name' => 'Patikul', 'province_id' => 98],
            ['name' => 'Siasi', 'province_id' => 98],
            ['name' => 'Talipao', 'province_id' => 98],
            ['name' => 'Tapul', 'province_id' => 98],

            // Tawi-Tawi
            ['name' => 'Bongao (Capital)', 'province_id' => 99],
            ['name' => 'Languyan', 'province_id' => 99],
            ['name' => 'Mapun (Cagayan de Tawi-Tawi)', 'province_id' => 99],
            ['name' => 'Panglima Sugala (Balimbing)', 'province_id' => 99],
            ['name' => 'Sapa-Sapa', 'province_id' => 99],
            ['name' => 'Sibutu', 'province_id' => 99],
            ['name' => 'Simunul', 'province_id' => 99],
            ['name' => 'Sitangkai', 'province_id' => 99],
            ['name' => 'South Ubian', 'province_id' => 99],
            ['name' => 'Tandubas', 'province_id' => 99],
            ['name' => 'Turtle Islands', 'province_id' => 99],

        ];

        foreach ($municipalities as $municipality) {
            Municipality::create([
                'name' => $municipality['name'],
                'province_id' => $municipality['province_id'],
            ]);
        }
    }
}
